name: Run CI Suite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel this run if a newer commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PAT_POC }} # non-github token Parinita's personal access token will expire ever 90 days
      - uses: ./.github/workflows/setup-workspace
      - run: pnpm -r run lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-workspace
      - run: pnpm -r run build
